{ self, inputs, ... }:
{
  flake.nixosModules.wallust =
    {
      pkgs,
      config,
      lib,
      ...
    }:
    let
      username = config.preferences.user.name;
    in
    {
      home-manager.users.${username} =
        { config, ... }:
        {
          programs.wallust = {
            enable = true;

            settings = {
              templates = {
                # Your existing Ghostty setup
                ghostty = {
                  template = "ghostty-colors.tmpl";
                  target = "~/.config/ghostty/themes/wallust";
                };

                # New: Yazi setup
                yazi = {
                  template = "yazi-colors.tmpl";
                  target = "~/.config/yazi/flavors/wallust.yazi/flavor.toml";
                };

                # New: Vesktop setup
                vesktop = {
                  template = "vesktop-colors.tmpl";
                  target = "~/.config/vesktop/themes/wallust.theme.css";
                };

                # NEW: Open Rgb
                openrgb_static = {
                  template = "openrgb_static.sh";
                  target = "~/.cache/wallust/openrgb_static.sh";
                };
              };
            };
          };

          # ---------------------------------------------------------
          # Template Target Directories (.keep)
          # ---------------------------------------------------------
          # Force Home Manager to create these directories so Wallust doesn't crash (os error 2)
          xdg.configFile."yazi/flavors/wallust.yazi/.keep".text = "";
          xdg.configFile."vesktop/themes/.keep".text = "";

          # ---------------------------------------------------------
          # Template Definitions
          # ---------------------------------------------------------

          # 1. Ghostty
          xdg.configFile."wallust/templates/ghostty-colors.tmpl".text = ''
            # Ghostty Wallust Template
            background = {{background}}
            foreground = {{foreground}}
            cursor-color = {{cursor}}
            selection-background = {{color8}}
            selection-foreground = {{foreground}}

            palette = 0={{color0}}
            palette = 1={{color1}}
            palette = 2={{color2}}
            palette = 3={{color3}}
            palette = 4={{color4}}
            palette = 5={{color5}}
            palette = 6={{color6}}
            palette = 7={{color7}}
            palette = 8={{color8}}
            palette = 9={{color9}}
            palette = 10={{color10}}
            palette = 11={{color11}}
            palette = 12={{color12}}
            palette = 13={{color13}}
            palette = 14={{color14}}
            palette = 15={{color15}}
          '';

          # 2. Yazi
          xdg.configFile."wallust/templates/yazi-colors.tmpl".text = ''
            [manager]
            cwd = { fg = "{{color4}}" }
            hovered = { fg = "{{background}}", bg = "{{color4}}" }
            preview_hovered = { underline = true }
            border_symbol = "│"
            border_style = { fg = "{{color8}}" }
          '';

          # 3. Vesktop
          xdg.configFile."wallust/templates/vesktop-colors.tmpl".text = ''
            /**
             * @name Wallust Theme (85% Opacity)
             * @description Dynamic theme generated by Wallust
             */
            .theme-dark, .theme-light, :root {
                /* Backgrounds set to 85% opacity */
                --background-primary: color-mix(in srgb, {{background}} 85%, transparent);
                --background-secondary: color-mix(in srgb, {{color0}} 85%, transparent);
                --background-secondary-alt: color-mix(in srgb, {{color0}} 85%, transparent);
                --background-tertiary: color-mix(in srgb, {{background}} 85%, transparent);
                --channeltextarea-background: color-mix(in srgb, {{color0}} 85%, transparent);
                
                /* Text and accents kept at 100% opacity for readability */
                --text-normal: {{foreground}};
                --text-muted: {{color8}};
                --header-primary: {{color4}};
                --interactive-normal: {{color6}};
                --interactive-hover: {{color7}};
                --interactive-active: {{color15}};
                --brand-experiment: {{color4}};
            }

            /* Force the base electron window layers to be transparent */
            body, #app-mount, .app_b1f720, .bg_d4b6c5 {
                background: transparent !important;
            }
          '';

          # --- MOVED INSIDE HOME MANAGER ---

          xdg.configFile."wallust/templates/openrgb_static.sh".text = ''
            #!/usr/bin/env bash
            ${pkgs.openrgb}/bin/openrgb --mode static --color {{color1 | strip}} >/dev/null 2>&1
          '';
        };
    };
}
